sudo: true
language: haskell

git:
  depth: 5

cache:
  directories:
    - "$HOME/.cabal"
    - "$HOME/.stack"
    - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:

    - ghc: 8.6.4
      env: GHCVER='8.6.4' CABALVER='head'
      os: linux
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.6.4
            - cabal-install-head

    - ghc: 8.6.4
      env: GHCVER='8.6.4' STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"
      os: linux
      addons:
        apt:
          packages:
            - libgmp-dev

install:
  - bash scripts/install.sh

script:
  - bash scripts/test.sh

  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint .

notifications:
  email: false
